### ISSUE TITLE
RegX

### ISSUE THREAD

**Issue by AdinAck** [AdinAck/Fantasy-Bike#4]
variables on nonvolatile memory

**Comment by AdinAck** [comment]
Completed:
- multiple instances can be run simultaneously
- more efficient in general
- powerful debugging tool

located [here](https://github.com/AdinAck/Fantasy-Bike/blob/master/%40motherboard/code/sd/RegX.py)

**Comment by AdinAck** [comment]
Turns out this is stupid and circuitpython has NVM built in I just couldn't find it before.

**Comment by chazack** [comment]
NVM = non-volatile memory?

Can you send me the email that you sent to Don so that I have the links for
your parts?
